---
- name: Install packages
  block:

  - name: Install packages
    become: true
    apt:
      name: "{{ item.name }}"
      state: present
      update_cache: yes
    loop: "{{ package_name }}"
  
-  name: Include common section
   block:
     
   - name: Common task  
     include_task: generic.yml
